### ISSUE TITLE
Improving README.md File For Better Readability.

### ISSUE THREAD

**Issue by kmalap05** [thepwnexperts/secure-coding#7]
**_Kedar Malap | Contributor | GSSOC'23_**

The documentation might be improved, and if you give it to me, I'll make sure you're not let down.

**Comment by thepwnexperts** [comment]
One contributor has already improved,you can contribute to other repositories. if you are only interested in this repository and can do more improvement then go ahead.

**Comment by thepwnexperts** [comment]
Sorry for late response

**Comment by kmalap05** [comment]
Verify the pull request, I have just made it more readable for users.
